### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by ngmoviedo** [bbaserdem/Matlab#1]
If I'm not mistaken, from what I've seen during my last installation of Matlab R2020a using this PKGBUILD, the instructions on how to obtain the tarball might need to be modified a bit:
Inside the download folder chosen the installer creates now two directories: "R2020a" and "MATLABConnector", being the contents of the first one the ones needed inside the tarball. If the complete download directory is inside the tarball that will lead to makepkg not been able to find the files.
Anyway, great PKGBUILD. Really useful.

**Comment by bbaserdem** [comment]
Thank you.

I did the installation as I described and did not have any hiccups. I did not find any directory named MATLABConnector. Maybe the installer changed very slightly from a month ago; but not sure.

Do note that I am about to move this repo to my general PKGBUILDS repo [here](https://github.com/bbaserdem/Arch/tree/master/matlab). I did tweak some stuff; but probably won't rebuild before 2020b. I suggest following there; (though I also have my system packages there usually) as I will delete this repo soon.

**Comment by bbaserdem** [comment]
I actually tested the installation again; and works without any hangups with the current instructions. Also the installer does not create any of the directories you mentioned. Here is an overview of the directory created with the new installer options; from which I have successfully built the package.

```
$ tree matlab -L 1
matlab
├── VersionInfo.xml
├── archives
├── bin
├── cefclient
├── help
├── install
├── installer_input.txt
├── java
├── license_agreement.txt
├── mathworks_installation_help.pdf
├── mathworks_installation_help_es.pdf
├── mathworks_installation_help_ja_JP.pdf
├── mathworks_installation_help_ko_KR.pdf
├── mathworks_installation_help_zh_CN.pdf
├── matlab_R2020a_glnxa64.zip
├── patents.txt
├── readme.txt
├── resources
├── sys
├── trademarks.txt
└── ui
```
